repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        name: gitleaks - detect secrets in staged changes
        entry: gitleaks protect --staged --verbose
        language: golang
        pass_filenames: false
